{
 "title": "Machine usage metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "machine_id",
    "label": "Machine Id",
    "query": {}
   },
   {
    "name": "metric_name",
    "label": "Metric",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "New tab", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Battery level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n       timestamp AS time,\n       value\nFROM metrics\nWHERE machine_id = ${machine_id:singlequote}\n  AND name = 'system.battery.utilization'\n  AND $__timeFilter(timestamp)\nORDER BY timestamp ASC;"
    }
   ]
  },
  {
   "title": "Charging",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value, timestamp FROM \"metrics\".\"metrics\" WHERE ( name = 'system.battery.charging' ) AND ( machine_id = ${machine_id:singlequote} ) ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Total anomaly events",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count() AS value\nFROM anomalies FINAL\nWHERE machine_id = ${machine_id:singlequote}\n  AND metric_name = ${metric_name:singlequote}\n  AND $__timeFilter(timestamp);"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n       m.value AS value,\n       m.timestamp AS time\nFROM metrics AS m\nWHERE m.machine_id = ${machine_id:singlequote}\n  AND m.name = 'system.memory.usage'\n  AND $__timeFilter(m.timestamp)\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n       m.value AS value,\n       m.timestamp AS time,\n       if(\n           m.metric_id IN (\n               SELECT metric_id\n               FROM anomalies\n               WHERE machine_id = ${machine_id:singlequote}\n                 AND metric_name = 'system.cpu.utilization'\n           ),\n           m.value,\n           NULL\n       ) AS anomaly\nFROM metrics AS m\nWHERE m.machine_id = ${machine_id:singlequote}\n  AND m.name = 'system.cpu.utilization'\n  AND $__timeFilter(m.timestamp)\nORDER BY time ASC;"
    }
   ]
  }
 ]
}