apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    isDefault: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      username: user
      defaultDatabase: metrics
    secureJsonData:
      password: password
